1.9.12=Resumo comparativo\\n\\
\\n\\
Totais\\n\\
- Adicionados: 56\\n\\
- Removidos: 126\\n\\
- Alterados: 13742\\n\\
\\n\\
Por modulo (top-level)\\n\\
- autoatendimento: +0/-0/~132\\n\\
- autoupdate.desktop: +0/-0/~26\\n\\
- autoupdate.webservice: +0/-0/~15\\n\\
- backgroundservices: +0/-0/~58\\n\\
- catraca: +0/-0/~104\\n\\
- catraca.webservice: +0/-0/~17\\n\\
- choppflux.common: +0/-0/~13\\n\\
- choppflux.webservice: +0/-0/~24\\n\\
- estacionamento.webservice: +0/-0/~15\\n\\
- fincatto.nfe: +0/-0/~3027\\n\\
- fiscal.common: +3/-2/~276\\n\\
- fiscal.webservice: +3/-1/~405\\n\\
- integracao.cm: +1/-0/~638\\n\\
- integracao.webapp: +0/-1/~187\\n\\
- lib.calendar: +0/-2/~74\\n\\
- lib.charts: +0/-2/~152\\n\\
- lib.cnab: +0/-2/~76\\n\\
- lib.common: +1/-2/~237\\n\\
- lib.dao: +7/-2/~1080\\n\\
- lib.elgin: +0/-2/~76\\n\\
- lib.model: +2/-2/~832\\n\\
- lib.relatorio: +0/-2/~306\\n\\
- lib.tef: +0/-2/~133\\n\\
- mail.webservice: +0/-0/~15\\n\\
- meucartao.common: +0/-0/~46\\n\\
- meucartao.webapp: +0/-0/~119\\n\\
- meucartao.webservice: +0/-0/~54\\n\\
- monitoracesso: +32/-0/~148\\n\\
- monitoracesso.sync: +0/-0/~4\\n\\
- monitoracesso.webapp: +1/-94/~87\\n\\
- monitoracesso.webservice: +0/-4/~58\\n\\
- monitorimpressao: +0/-0/~42\\n\\
- pdv: +0/-0/~387\\n\\
- portal.common: +0/-0/~64\\n\\
- portal.webapp: +0/-0/~135\\n\\
- portal.webservice: +0/-0/~35\\n\\
- pos.webservice: +0/-1/~126\\n\\
- posgertec.android: +0/-1/~301\\n\\
- posgo.android: +0/-1/~264\\n\\
- posgo.common: +0/-0/~48\\n\\
- posgo.webservice: +0/-0/~47\\n\\
- resultados.common: +0/-0/~37\\n\\
- resultados.webapp: +0/-0/~93\\n\\
- resultados.webservice: +0/-0/~27\\n\\
- retaguarda: +6/-1/~2687\\n\\
- smartlocker.webservice: +0/-0/~22\\n\\
- socius.mobile: +0/-0/~40\\n\\
- socius.webservice: +0/-2/~302\\n\\
- storage.webservice: +0/-0/~15\\n\\
- talonario.common: +0/-0/~25\\n\\
- talonario.webapp: +0/-0/~82\\n\\
- talonario.webservice: +0/-0/~21\\n\\
- vmpay.common: +0/-0/~13\\n\\
- vmpay.webservice: +0/-0/~21\\n\\
- voucher.common: +0/-0/~105\\n\\
- voucher.webapp: +0/-0/~260\\n\\
- voucher.webservice: +0/-0/~109

1.9.13=Resumo comparativo\\n\\
\\n\\
Totais\\n\\
- Adicionados: 805\\n\\
- Removidos: 259\\n\\
- Alterados: 13539\\n\\
\\n\\
Por modulo (top-level)\\n\\
- .classpath: +1/-0/~0\\n\\
- .project: +1/-0/~0\\n\\
- autoatendimento: +0/-0/~132\\n\\
- autoupdate.desktop: +0/-0/~26\\n\\
- autoupdate.webservice: +0/-0/~15\\n\\
- backgroundservices: +0/-0/~58\\n\\
- catraca: +0/-0/~104\\n\\
- catraca.webservice: +0/-0/~17\\n\\
- choppflux.common: +0/-0/~13\\n\\
- choppflux.webservice: +0/-0/~24\\n\\
- estacionamento.webservice: +0/-0/~15\\n\\
- fincatto.nfe: +0/-0/~3027\\n\\
- fiscal.common: +4/-107/~172\\n\\
- fiscal.webservice: +0/-147/~261\\n\\
- integracao.cm: +0/-1/~638\\n\\
- integracao.webapp: +95/-0/~187\\n\\
- lib.calendar: +2/-0/~74\\n\\
- lib.charts: +2/-0/~152\\n\\
- lib.cnab: +2/-0/~76\\n\\
- lib.common: +7/-1/~237\\n\\
- lib.dao: +8/-2/~1085\\n\\
- lib.elgin: +2/-0/~76\\n\\
- lib.model: +42/-1/~833\\n\\
- lib.relatorio: +2/-0/~306\\n\\
- lib.tef: +2/-0/~133\\n\\
- mail.webservice: +0/-0/~15\\n\\
- meucartao.common: +0/-0/~46\\n\\
- meucartao.webapp: +0/-0/~119\\n\\
- meucartao.webservice: +0/-0/~54\\n\\
- monitoracesso: +0/-0/~180\\n\\
- monitoracesso.sync: +0/-0/~4\\n\\
- monitoracesso.webapp: +0/-0/~88\\n\\
- monitoracesso.webservice: +2/-0/~58\\n\\
- monitorimpressao: +0/-0/~42\\n\\
- nfse.webservice: +624/-0/~0\\n\\
- pdv: +0/-0/~387\\n\\
- portal.common: +0/-0/~64\\n\\
- portal.webapp: +0/-0/~135\\n\\
- portal.webservice: +0/-0/~35\\n\\
- pos.webservice: +1/-0/~126\\n\\
- posgertec.android: +1/-0/~301\\n\\
- posgo.android: +1/-0/~264\\n\\
- posgo.common: +0/-0/~48\\n\\
- posgo.webservice: +0/-0/~47\\n\\
- resultados.common: +0/-0/~37\\n\\
- resultados.webapp: +0/-0/~93\\n\\
- resultados.webservice: +0/-0/~27\\n\\
- retaguarda: +4/-0/~2693\\n\\
- smartlocker.webservice: +0/-0/~22\\n\\
- socius.mobile: +0/-0/~40\\n\\
- socius.webservice: +2/-0/~302\\n\\
- storage.webservice: +0/-0/~15\\n\\
- talonario.common: +0/-0/~25\\n\\
- talonario.webapp: +0/-0/~82\\n\\
- talonario.webservice: +0/-0/~21\\n\\
- vmpay.common: +0/-0/~13\\n\\
- vmpay.webservice: +0/-0/~21\\n\\
- voucher.common: +0/-0/~105\\n\\
- voucher.webapp: +0/-0/~260\\n\\
- voucher.webservice: +0/-0/~109

